In [1]:
import torch
from einops import rearrange, einsum

In [2]:
dim_by = torch.linspace(start=0.0, end=1.0, steps=10)

In [3]:
dim_by

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [2]:
import torch

In [3]:
a = torch.randn(4, 3)
a

tensor([[-0.4381, -0.4343,  2.1163],
        [-0.1206, -1.1688,  0.2679],
        [-1.6929, -0.1880, -0.6294],
        [ 0.1435, -0.7223, -0.0644]])

In [4]:
b = torch.sum(a, dim=-1)

In [5]:
b

tensor([ 1.2439, -1.0215, -2.5103, -0.6433])

In [3]:
a = torch.arange(0, 10, 2)

In [4]:
a

tensor([0, 2, 4, 6, 8])

In [12]:
import torch

In [19]:
a = torch.tensor([[1,4,5], [6,5,2]])

In [20]:
a

tensor([[1, 4, 5],
        [6, 5, 2]])

In [21]:
max_value = torch.max(a, dim=0).values

In [22]:
max_value

tensor([6, 5, 5])

In [23]:
a = a - max_value

In [24]:
a

tensor([[-5, -1,  0],
        [ 0,  0, -3]])

In [25]:
mask = torch.tril(torch.ones(3, 3, dtype=torch.bool))

In [26]:
mask

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [36]:
a = torch.ones((2, 4, 8))

In [37]:
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [38]:
a.shape

torch.Size([2, 4, 8])

In [39]:
from einops import einsum, rearrange

In [40]:
a = rearrange(a, "... seq_len (num_heads d_k) -> ... num_heads seq_len d_k", num_heads=4)

In [41]:
a.shape

torch.Size([2, 4, 4, 2])

In [43]:
a = rearrange(a, "... num_heads seq_len d_k -> (... num_heads) seq_len d_k")

In [44]:
a.shape

torch.Size([8, 4, 2])

In [1]:
import torch

In [2]:
a = torch.ones(16, 4)

In [3]:
b = torch.tensor([[0, 3, 4], [5, 6, 7]])

In [5]:
(a[b]).shape

torch.Size([2, 3, 4])