In [1]:
import torch
from einops import rearrange, einsum

In [2]:
dim_by = torch.linspace(start=0.0, end=1.0, steps=10)

In [3]:
dim_by

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [2]:
import torch

In [3]:
a = torch.randn(4, 3)
a

tensor([[-0.4381, -0.4343,  2.1163],
        [-0.1206, -1.1688,  0.2679],
        [-1.6929, -0.1880, -0.6294],
        [ 0.1435, -0.7223, -0.0644]])

In [4]:
b = torch.sum(a, dim=-1)

In [5]:
b

tensor([ 1.2439, -1.0215, -2.5103, -0.6433])

In [3]:
a = torch.arange(0, 10, 2)

In [4]:
a

tensor([0, 2, 4, 6, 8])